name: Daily Date Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 12:00 AM UTC
  workflow_dispatch:

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with today's date
        run: |
          DATE=$(date -u +"%A, %B %d, %Y")
          echo -e "# What day is it?\n\nToday is: 🤖 *$DATE*" > README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📅 Updated: $(date -u +"%A, %B %d, %Y")"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
